import fs from 'node:fs';

const file = 'public/index.html';
let html = fs.readFileSync(file, 'utf8');

html = html.replace(/<title>[^<]*<\/title>/, '<title>Local Chrome Tools for Private Work | Wendygo Studio</title>');
html = html.replace(/<meta name="description" content="[^"]*">/, '<meta name="description" content="Six local-first Chrome extensions for text, images, files, infrastructure, EU claims and focus. No account required.">');
html = html.replace(/<h1>[^<]*<em>Chrome Extensions<\/em><\/h1>/, '<h1>Local tools for better work <em>in Chrome</em></h1>');
html = html.replace(/<a class="cta-primary" href="#products">[\s\S]*?<\/a>/, '<a class="cta-primary" href="#find-your-tool">Find your tool</a>');
html = html.replace('<a class="cta-ghost" href="/blog/">Read the blog</a>', '<a class="cta-ghost" href="/blog/">Read practical guides</a>');

const schema = `<script type="application/ld+json">{"@context":"https://schema.org","@type":"WebSite","name":"Wendygo Studio","url":"https://wendygostudio.com/","inLanguage":"en","potentialAction":{"@type":"SearchAction","target":"https://wendygostudio.com/blog/?q={search_term_string}","query-input":"required name=search_term_string"}}</script>\n<script type="application/ld+json">{"@context":"https://schema.org","@type":"ItemList","name":"Wendygo Studio Chrome extensions","itemListElement":[{"@type":"ListItem","position":1,"url":"https://wendygostudio.com/textforge/","name":"TextForge"},{"@type":"ListItem","position":2,"url":"https://wendygostudio.com/frameforge/","name":"FrameForge"},{"@type":"ListItem","position":3,"url":"https://wendygostudio.com/scrubforge/","name":"ScrubForge"},{"@type":"ListItem","position":4,"url":"https://wendygostudio.com/claimforge/","name":"ClaimForge"},{"@type":"ListItem","position":5,"url":"https://wendygostudio.com/convertforge/","name":"ConvertForge"},{"@type":"ListItem","position":6,"url":"https://wendygostudio.com/slimeforge/","name":"SlimeForge"}]}</script>`;
html = html.replace('</body>', `${schema}\n</body>`);

const styles = `<style id="home-conversion-styles">.home-use-cases{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:30px}.home-use-case{display:flex;flex-direction:column;gap:7px;padding:20px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.025);color:inherit;text-decoration:none;transition:border-color .2s,transform .2s}.home-use-case:hover{border-color:var(--amber);transform:translateY(-2px)}.home-use-case strong{font-size:17px;color:var(--ink)}.home-use-case span{color:var(--muted);font-size:14px}.home-comparison{overflow:auto;margin-top:28px;border:1px solid var(--line);border-radius:14px}.home-comparison table{width:100%;border-collapse:collapse;min-width:620px}.home-comparison th,.home-comparison td{padding:14px 16px;text-align:left;border-bottom:1px solid var(--line)}.home-comparison th{color:var(--amber);font-size:12px;text-transform:uppercase;letter-spacing:.08em}.home-comparison tr:last-child td{border-bottom:0}.product-card-featured{border-color:var(--amber);box-shadow:0 0 0 1px rgba(232,163,61,.18),0 18px 42px rgba(0,0,0,.16)}.product-featured-label{display:inline-flex;align-items:center;gap:6px;margin:-8px 0 14px;padding:5px 9px;border:1px solid rgba(232,163,61,.5);border-radius:999px;color:var(--amber);font-size:11px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.home-proof{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:28px}.home-proof div{padding:16px;border:1px solid var(--line);border-radius:12px}.home-proof strong{display:block;color:var(--amber);font-size:20px}.home-proof span{display:block;margin-top:4px;color:var(--muted);font-size:13px}@media(max-width:800px){.home-use-cases{grid-template-columns:repeat(2,minmax(0,1fr))}.home-proof{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.home-use-cases{grid-template-columns:1fr}.home-proof{grid-template-columns:1fr}.home-comparison{margin-left:-4px;margin-right:-4px}}</style>`;
html = html.replace('</head>', `${styles}\n</head>`);

const useCases = `  <section class="section" id="find-your-tool">\n    <div class="section-inner">\n      <div class="section-label">Start with a job</div>\n      <h2 class="section-title">What are you trying to do?</h2>\n      <p class="section-sub">Choose the workflow that matches your next task. Each card takes you straight to the Forge built for it.</p>\n      <div class="home-use-cases">\n        <a class="home-use-case" href="#product-textforge"><strong>Clean or transform text</strong><span>Extract, format, encode and build repeatable recipes → TextForge</span></a>\n        <a class="home-use-case" href="#product-frameforge"><strong>Prepare an image</strong><span>Resize, crop, enhance and export social-ready files → FrameForge</span></a>\n        <a class="home-use-case" href="#product-convertforge"><strong>Convert a file locally</strong><span>Drop images, documents, audio or data into the right converter → ConvertForge</span></a>\n        <a class="home-use-case" href="#product-scrubforge"><strong>Share a sensitive config</strong><span>Sanitize secrets while preserving useful structure → ScrubForge</span></a>\n        <a class="home-use-case" href="#product-claimforge"><strong>Make a consumer claim</strong><span>Understand EU routes and prepare a clearer letter → ClaimForge</span></a>\n        <a class="home-use-case" href="#product-slimeforge"><strong>Restart a focus habit</strong><span>Turn each Pomodoro session into progress for a growing pet → SlimeForge</span></a>\n      </div>\n      <div class="home-proof" aria-label="Wendygo Studio principles"><div><strong>6</strong><span>focused browser tools</span></div><div><strong>0</strong><span>Wendygo content-processing servers</span></div><div><strong>5 days</strong><span>free PRO trial, no card</span></div><div><strong>6</strong><span>interface languages</span></div></div>\n    </div>\n  </section>\n\n`;
html = html.replace('  <section class="section products" id="products">', `${useCases}  <section class="section products" id="products">`);

for (const [name, id] of [['TextForge','textforge'],['FrameForge','frameforge'],['ScrubForge','scrubforge'],['ClaimForge','claimforge'],['ConvertForge','convertforge']]) {
  html = html.replace(`<!-- ${name} -->\n        <div class="product-card">`, `<!-- ${name} -->\n        <div class="product-card" id="product-${id}">`);
}
html = html.replace('<!-- SlimeForge -->\n        <div class="product-card">', '<!-- SlimeForge -->\n        <div class="product-card product-card-featured" id="product-slimeforge">\n          <div class="product-featured-label">★ Most engaging in current GA4 signal</div>');
html = html.replaceAll('>Learn more</a>', '>Try this Forge</a>');
html = html.replace('>We do not collect, store or transmit any personal data or usage analytics.</div>', '>We do not collect, store or transmit your extension content. Minimal product events such as installs and sessions may be measured in aggregate to improve the tools.</div>');

const compare = `  <section class="section" id="compare">\n    <div class="section-inner">\n      <div class="section-label">Choose with confidence</div>\n      <h2 class="section-title">One ecosystem, different jobs</h2>\n      <p class="section-sub">Every Forge has a free tier, no account requirement and local-first core processing.</p>\n      <div class="home-comparison"><table><thead><tr><th>Need</th><th>Forge</th><th>Core processing</th><th>Account</th></tr></thead><tbody>\n        <tr><td>Text cleanup and transforms</td><td><a href="/textforge/">TextForge</a></td><td>On device</td><td>Not required</td></tr>\n        <tr><td>Images and social sizes</td><td><a href="/frameforge/">FrameForge</a></td><td>On device</td><td>Not required</td></tr>\n        <tr><td>File conversion</td><td><a href="/convertforge/">ConvertForge</a></td><td>On device</td><td>Not required</td></tr>\n        <tr><td>Network config sanitization</td><td><a href="/scrubforge/">ScrubForge</a></td><td>Local / BYOK optional</td><td>Not required</td></tr>\n        <tr><td>EU consumer claims</td><td><a href="/claimforge/">ClaimForge</a></td><td>On device</td><td>Not required</td></tr>\n        <tr><td>Focus sessions</td><td><a href="/slimeforge/">SlimeForge</a></td><td>On device</td><td>Not required</td></tr>\n      </tbody></table></div>\n      <div class="hero-ctas" style="margin-top:28px;margin-bottom:0"><a class="cta-primary" href="#products">See all six tools</a><a class="cta-ghost" href="/privacy">Read the privacy policy</a></div>\n    </div>\n  </section>\n\n`;
html = html.replace('</body>', `${compare}</body>`);
fs.writeFileSync(file, html);
