import fs from 'node:fs'; import path from 'node:path';
const root=path.resolve('public'), files=[]; function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?walk(p):e.name.endsWith('.html')&&files.push(p)}} walk(root);
const errors=[]; const canonicals=new Map();const decodeEntities=value=>value.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const redirectSources=new Set(fs.readFileSync(path.join(root,'_redirects'),'utf8').split(/\r?\n/).map(line=>line.trim()).filter(line=>line&&!line.startsWith('#')).map(line=>line.split(/\s+/)[0]));
function localTargetExists(href){const clean=href.split('#')[0].split('?')[0];if(!clean||!clean.startsWith('/')||clean.startsWith('//'))return true;if(redirectSources.has(clean)||redirectSources.has(`${clean}*`))return true;const rel=decodeURIComponent(clean).replace(/^\/+|\/+$/g,'');return fs.existsSync(path.join(root,rel,'index.html'))||fs.existsSync(path.join(root,`${rel}.html`))||fs.existsSync(path.join(root,rel));}
for(const f of files){const s=fs.readFileSync(f,'utf8'); const rel=path.relative(root,f).replaceAll('\\','/'); const noindex=/<meta\s+name=["']robots["']\s+content=["'][^"']*noindex/i.test(s); const title=s.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim(); const desc=s.match(/<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i)?.[1]; const can=s.match(/<link\s+rel=["']canonical["']\s+href=["']([^"']*)["']/i)?.[1]; if(!title)errors.push(`${rel}: missing title`);else if([...decodeEntities(title)].length>60)errors.push(`${rel}: title ${[...decodeEntities(title)].length}`);if(desc&&[...decodeEntities(desc)].length>150)errors.push(`${rel}: description ${[...decodeEntities(desc)].length}`);if(!can&&!noindex)errors.push(`${rel}: missing canonical`);if(can&&!noindex){if(canonicals.has(can))errors.push(`${rel}: duplicate canonical ${can}`);canonicals.set(can,rel)}if(!s.includes('static.cloudflareinsights.com/beacon.min.js'))errors.push(`${rel}: missing analytics`);if(/<meta[^>]+content=["'][^"']*&(?!(?:amp|quot|lt|gt|#\d+|#x[0-9a-f]+);)/i.test(s))errors.push(`${rel}: unescaped ampersand in meta content`);for(const m of s.matchAll(/href=["']([^"']+)["']/gi)){if(!localTargetExists(m[1]))errors.push(`${rel}: broken internal link ${m[1]}`)}try{for(const m of s.matchAll(/<script\s+type=["']application\/ld\+json["']>([\s\S]*?)<\/script>/gi))JSON.parse(m[1])}catch(e){errors.push(`${rel}: invalid JSON-LD`)}}
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
const sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');const sitemapUrls=new Set([...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1]));for(const url of canonicals.keys())if(!sitemapUrls.has(url))errors.push(`sitemap missing ${url}`);for(const url of sitemapUrls)if(!canonicals.has(url))errors.push(`sitemap has noncanonical ${url}`);if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log(`${files.length} HTML files; ${errors.length} errors`);
